#\u8BBE\u7F6E\u4E00\u7EA7\u8DEF\u5F84
server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zl123
    url: jdbc:mysql://localhost:3306/t122new?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai

mybatis:
  type-aliases-package: com.zl.entity,com.zl.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zl:
        mapper: debug
